"""
split_config.py -- AUTO-GENERATED by patient_split.py. Do not edit by hand;
re-run patient_split.py if you need a different split.

Generated: 2026-08-03T06:54:48.115731+00:00
Final optimizer cost: 0.01961

Per-class train/test beat counts at generation time:
  N: train=71106 test=19019 total=90125 (train 78.9%)
  S: train=2234 test=547 total=2781 (train 80.3%)
  V: train=5333 test=1676 total=7009 (train 76.1%)
  F: train=748 test=55 total=803 (train 93.2%)
  Q: train=15 test=0 total=15 (train 100.0%)
"""

DS1_RECORDS = [100, 101, 103, 105, 106, 108, 109, 111, 112, 113, 115, 116, 117, 119, 121, 122, 123, 200, 201, 202, 203, 207, 208, 209, 212, 213, 214, 215, 219, 221, 228, 230, 231, 232, 234]
DS2_RECORDS = [114, 118, 124, 205, 210, 220, 222, 223, 233]
